# (Auto-generated by buildozer init; edit as needed)
[app]
title = Wav2LipKivyDemo
package.name = wav2lipkivydemo
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = kivy, numpy, torch, opencv-python
orientation = portrait
fullscreen = 1

# (other settings: see official Buildozer docs)